"use client";

import Link from "next/link";
import React from "react";
import { motion } from "framer-motion";
import { FaCheck } from "react-icons/fa";
import { MdOutlineCelebration } from "react-icons/md";

interface MealFormData {
  weight: string;
  goal: string;
  gender: string;
  mealPlanType: string;
  workoutDecision: string;
  age: string;
}

interface CreateMealStep7Props {
  formData: MealFormData;
}

const CreateMealStep7: React.FC<CreateMealStep7Props> = ({ formData }) => {
  const queryString = new URLSearchParams({ ...formData }).toString();
  const myMealsUrl = `/mymeals?${queryString}`;

  return (
    <motion.div
      className="w-full h-fit flex flex-col items-center justify-center gap-y-8 p-4"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      <motion.div
        className="w-fit h-fit text-center"
        initial={{ scale: 0.9 }}
        animate={{ scale: 1 }}
        transition={{ duration: 0.3 }}
      >
        <h1 className="text-2xl sm:text-3xl font-bold text-white flex flex-col sm:flex-row gap-3 items-center justify-center">
          <motion.span
            animate={{ rotate: [0, 10, -10, 0] }}
            transition={{ repeat: Infinity, duration: 4, ease: "easeInOut" }}
          >
            <MdOutlineCelebration className="text-3xl" />
          </motion.span>
          Thank You For Creating Your Meal Plan!
          <motion.span
            animate={{ rotate: [0, -10, 10, 0] }}
            transition={{ repeat: Infinity, duration: 4, ease: "easeInOut", delay: 0.2 }}
          >
            <MdOutlineCelebration className="text-3xl" />
          </motion.span>
        </h1>
      </motion.div>

      <motion.div
        className="w-16 h-16 bg-white text-black rounded-full flex justify-center items-center text-3xl"
        initial={{ scale: 0 }}
        animate={{ scale: 1 }}
        transition={{ 
          type: "spring",
          stiffness: 260,
          damping: 20,
          delay: 0.3
        }}
      >
        <FaCheck />
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
      >
        <Link href={myMealsUrl} passHref>
          <motion.button
            className="mt-4 px-8 py-3 bg-white text-black cursor-pointer rounded-full font-medium text-lg hover:bg-black hover:text-white transition-all duration-300 shadow-lg hover:shadow-xl"
            whileHover={{ 
              scale: 1.05,
              boxShadow: "0 5px 15px rgba(255, 255, 255, 0.3)"
            }}
            whileTap={{ scale: 0.95 }}
          >
            Generate My Meal Plan
          </motion.button>
        </Link>
      </motion.div>

      <motion.div 
        className="text-gray-300 text-center max-w-md"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.7 }}
      >
        <p>Your personalized meal plan is being prepared!</p>
        <p className="mt-2 text-sm">Click the button above to view your customized recommendations generated by AI.</p>
      </motion.div>
    </motion.div>
  );
};

export default CreateMealStep7;